version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    day: monday
  open-pull-requests-limit: 5
  target-branch: develop
  
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    day: monday
  open-pull-requests-limit: 5
  target-branch: develop
