version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: flowboard
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flowboard_development
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U flowboard"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
