services:
  # Web Service - Rails Application
  - type: web
    name: flowboard
    runtime: ruby
    plan: free
    buildCommand: |
      bundle install
      npm install
      npm run build
      npm run build:css
      bundle exec rails assets:precompile
      bundle exec rails db:migrate
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: flowboard-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: flowboard-redis
          property: connectionString

  # Background Worker - Sidekiq
  - type: worker
    name: flowboard-sidekiq
    runtime: ruby
    plan: free
    buildCommand: bundle install
    startCommand: bundle exec sidekiq
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: flowboard-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: flowboard-redis
          property: connectionString

databases:
  # PostgreSQL Database
  - name: flowboard-db
    databaseName: flowboard_production
    user: flowboard
    plan: free

  # Redis Instance
  - name: flowboard-redis
    plan: free
