services:
  # Web Service - Rails Application (Docker)
  - type: web
    name: flowboard
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: flowboard-db
          property: connectionString

databases:
  # PostgreSQL Database
  - name: flowboard-db
    databaseName: flowboard_production
    user: flowboard
    plan: free
