name: Deploy to Render

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Render
        env:
          RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          if [ -n "$RENDER_DEPLOY_HOOK_URL" ]; then
            echo "🚀 Triggering deployment on Render..."
            curl -X POST "$RENDER_DEPLOY_HOOK_URL"
            echo "✅ Deployment triggered successfully!"
          else
            echo "⚠️  RENDER_DEPLOY_HOOK_URL not configured."
            echo "To enable auto-deploy:"
            echo "1. Create a Web Service on Render.com"
            echo "2. Get the Deploy Hook URL from Settings"
            echo "3. Add it as RENDER_DEPLOY_HOOK_URL in GitHub Secrets"
          fi

      - name: Deployment Status
        run: |
          echo "📊 Deployment Summary:"
          echo "  - Branch: ${{ github.ref_name }}"
          echo "  - Commit: ${{ github.sha }}"
          echo "  - Author: ${{ github.actor }}"
          echo ""
          echo "Check your Render dashboard for deployment progress:"
          echo "https://dashboard.render.com"
